#companyInfo微服务

#服务端口
server:
  port: 8500
#服务名
spring:
  application:
    name: service-companyInfo
  #MYSQL数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/company?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #配置自动建表
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/  #将服务注册到注册中心


